### ISSUE TITLE
Please support more "current" templates... :-)

### ISSUE THREAD

**Issue by Bascht74** [jcwillox/hass-template-climate#1]
Hi, 

I tried your integration and I am very happy with it. I expected this to be in the HA core, but it isn't. 
Great, that you made this available!

One thing I am missing are the following templates for UI: 
- `target_temperature_template` for the current target temperature that the device is using, 
- `hvac_mode_template` for the current hvac mode that the device is using, 
- `hvac_action_template` for the current state: heating / cooling / idle / off,
- `fan_mode_template` for the current fan mode hat the device is using.

You already got the current swing mode via `swing_mode_template`, but the others are missing. 

Why this request?
I got an device that can be configured via it's own panel and if it is set to off or another mode there or when the target temperature is changed, the HA mode / temperature doesn't reflect that. 

new example with the new stuff:
```
climate:
  - platform: climate_template
    name: Bedroom Aircon
    modes:
      - "auto"
      - "dry"
      - "off"
      - "cool"
      - "fan_only"
    min_temp: 16
    max_temp: 30
    
    # get current temp.
    current_temperature_template: "{{ states('sensor.bedroom_temperature') }}"  
    
    # get current humidity.
    current_humidity_template: "{{ states('sensor.bedroom_humidity') }}"

    # get current target temperature for UI. --> suggested change
    target_temperature_template: "{{ states('sensor.bedroom_target_temperature') }}"

    # get current hvac mode for UI. --> suggested change
    hvac_mode_template: "{{ states('sensor.bedroom_hvac_mode') }}"

    # get current hvac state (idle, cooling, heating, off) for UI. --> suggested change
    hvac_action_template: "{{ states('sensor.bedroom_hvac_state') }}"

    # get current fan mode for UI. --> suggested change
    fan_mode_template: "{{ states('sensor.bedroom_fan_mode') }}"
    
    # swing mode switch for UI.  --> already there!!!!!!!
    swing_mode_template: "{{ states('input_boolean.bedroom_swing_mode') }}"
    
    # available based on esphome nodes' availability.
    availability_template: "{{ is_state('binary_sensor.bedroom_node_status', 'on') }}"

    # Example Action.
    set_hvac_mode:
    
      # allows me to disable sending commands to aircon via UI.
      - condition: state  
        entity_id: input_boolean.enable_aircon_controller
        state: "on"
        
      # send the climates current state to esphome.
      - service: esphome.bedroom_node_aircon_state  
        data_template:
          temperature: "{{ state_attr('climate.bedroom_aircon', 'temperature') | int }}"
          operation_mode: "{{ states('climate.bedroom_aircon') }}"
          fan_mode: "{{ state_attr('climate.bedroom_aircon', 'fan_mode') }}"
          swing_mode: "{{ is_state_attr('climate.bedroom_aircon', 'swing_mode', 'on') }}"
          light: "{{ is_state('light.bedroom_aircon_light', 'on') }}"

```
