### ISSUE TITLE
[FR]: Add swing positions

### ISSUE THREAD

**Issue by zastrixarundell** [jcwillox/hass-template-climate#103]
### Is your feature request related to a problem? Please describe.

My current AC has the option of setting vertical and horizontal swing modes. Right now it's only a binary in the template.

There's: `auto`, `low`, `medium`, `high` for both horizontal and vertrical.

### Describe the solution you'd like

[Tasmota-IRHVAC](https://github.com/hristo-atanasov/Tasmota-IRHVAC) has these options kinda so I'll take inspiration from it:
```yml
    supported_swing_list:
      - "off"
      - "vertical" #up to down
      # - "horizontal" # Left to right
      # - "both"
```

Adding something like:
```yml
supported_swing_modes:
  horizontal:
    - low
    - medium
    - high
    - auto
  vertical:
    - low
    - medium
    - high
    - auto
```
