### ISSUE TITLE
error message when updating target temperature

### ISSUE THREAD

**Issue by DohmenICT** [jcwillox/hass-template-climate#15]
Hi!

I have an heat-pump which I can control via modbus. I have the following configuration:
```
  - platform: climate_template
    name: Circuit1
    modes:
      - "auto"
      - "heat"
      - "off"
      - "cool"
    min_temp: 20
    max_temp: 35
    # get current temp.
    current_temperature_template: "{{ states('sensor.room_air_temp_circuit1') }}"
    target_temperature_template: "{{ states('sensor.target_temp_circuit1') }}"
    set_temperature:
        - service: modbus.write_register
          data_template:
            address: 2
            slave: 1
            hub: lg_modbus
            value: "{{ state_attr('climate.circuit1', 'temperature') | int * 10 }}"
```

The value that I need to write to the register is an integer with the temperature times 10. So 23.0 would be 230. This works.

When I adjust the target temperature I get this error message:
```
Logger: homeassistant.helpers.script.circuit1
Source: helpers/script.py:1428
First occurred: 11:22:40 (1 occurrences)
Last logged: 11:22:40

Circuit1: Running script requires passing in a context
```

Any idea what is going on here?
