### ISSUE TITLE
Making a climate element

### ISSUE THREAD

**Issue by Jens-Wymeersch** [jcwillox/hass-template-climate#16]
@jcwillox you wrote in your documentation that IR codes would be possible. However, I'm struggling a bit and hope to get some help. 
I have a temperature sensor, a Broadlink device (IR) and an input boolean for the state based on power consumption via a smart plug. Aim is to get a simple climate element which I can see the state, put it on/off and increase or decrease the temperature.

I started making the template, but I'm stuck and need some guidance.

```
- platform: climate_template
  name: Bedroom Aircon
  modes:
    - "on"
    - "off"
  min_temp: 20
  max_temp: 30

  current_temperature_template: "{{ states('sensor.remote_apt_temperature') }}"

  current_humidity_template: "{{ states('sensor.remote_apt_humidity') }}"

  set_hvac_mode:
    - condition: state
      entity_id: input_boolean.apt_airco

    - service:
```

**Comment by jcwillox** [comment]
It can however the way I did it was with a service call to an ESPHome device and a custom bit of C code on that device to make use of the [IRremoteESP8266](https://github.com/crankyoldgit/IRremoteESP8266) library, to construct and send the IR message. I don't have any experience with the Broadlink integration for Home Assistant, and I'm not sure how well it will work for this as aircons don't have discrete on/off or cool/fan IR codes, instead, they send the entire "state" of the aircon in one message.

In case it helps here's the configuration I use for my aircon.
```yaml
climate:
  - platform: climate_template
    name: Bedroom Aircon
    modes:
      - "auto"
      - "dry"
      - "off"
      - "cool"
      - "fan_only"
    min_temp: 16
    max_temp: 30

    current_temperature_template: '{{ states("sensor.bedroom_temperature") }}'
    current_humidity_template: '{{ states("sensor.bedroom_humidity") }}'
    swing_mode_template: '{{ states("input_boolean.bedroom_swing_mode") }}'
    availability_template: '{{ is_state("binary_sensor.bedroom_node_status", "on") }}'

    set_hvac_mode:
      service: script.update_aircon_state

    set_fan_mode:
      service: script.update_aircon_state

    set_temperature:
      service: script.update_aircon_state

    set_swing_mode:
      service: script.update_aircon_state
```

```yaml
script:
  update_aircon_state:
    alias: "Update Aircon State"
    sequence:
      - condition: state
        entity_id: input_boolean.enable_aircon_controller
        state: "on"
      - service: esphome.bedroom_node_aircon_state
        data:
          temperature: '{{ state_attr("climate.bedroom_aircon", "temperature") | int }}'
          operation_mode: '{{ states("climate.bedroom_aircon") }}'
          fan_mode: '{{ state_attr("climate.bedroom_aircon", "fan_mode") }}'
          swing_mode: '{{ is_state_attr("climate.bedroom_aircon", "swing_mode", "on") }}'
          light: >
            {% if light is defined %}
              {{ light }}
            {% else %}
              {{ is_state("light.bedroom_aircon_light", "on") }}
            {% endif %}
```

**Comment by Jens-Wymeersch** [comment]
@jcwillox josh, thank you for your quick reply. The question is more how you map the values to update the 'new' entity.
You are for example working with scripts whereas I am working switches.

**Comment by jcwillox** [comment]
Is this more what your aiming for, to turn a switch on/off based on the aircon state.

The section below `set_hvac_mode` is just a standard automation action, so I generated this quickly with the UI and then copied the YAML version.

```yaml
# ...
    set_hvac_mode:
      if:
        - condition: state
          entity_id: climate.bedroom_aircon
          state: "off"
      then:
        - service: switch.turn_off
          data: {}
          target:
            entity_id: switch.aircon
      else:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.aircon
```
