### ISSUE TITLE
Template based on a Daikin Climate

### ISSUE THREAD

**Issue by NdR91** [jcwillox/hass-template-climate#17]
Hello,

I'm trying to use this component in order to replicate my Daikin AC already integrated in Home Assistant.
Why? Because i temporarly need to change how it displays the "Swing Mode" and the "Fan Mode". Currently the integration call those features in a non-standard way, causing an incompatibility with Home Kit.

So, this is my code:

```yaml
climate:
  - platform: climate_template
    name: Daikin Studio HomeKit
    # available based on esphome nodes' availability.
    availability_template:  >-
      {% if states('climate.daikin_studio') in ['fan_only', 'dry', 'cool', 'heat', 'heat_cool', 'off']  %}
        true
      {% else %}
        false
      {% endif %}

    # get current temp.
    current_temperature_template: "{{ states.climate.daikin_studio.attributes.current_temperature }}"

    # get current humidity.
    current_humidity_template: "{{ states('sensor.cucina_humidity_filtered') }}"

    # hvac mode switch for UI.
    hvac_mode_template: >-
      {% if states('sensor.climate.daikin_studio'), 'off' %}
        off
      {% elif states('sensor.climate.daikin_studio'), 'fan_only' %}
        fan_only
      {% elif states('sensor.climate.daikin_studio'), 'dry' %}
        dry
      {% elif states('sensor.climate.daikin_studio'), 'cool' %}
        cool
      {% elif states('sensor.climate.daikin_studio'), 'heat' %}
        heat
      {% elif states('sensor.climate.daikin_studio'), 'heat_cool' %}
        heat_cool
      {% else %}
      {% endif %}

    # swing mode switch for UI.
    swing_mode_template: >-
      {% if is_state_attr('climate.daikin_studio', 'swing_mode', 'Off') %}
        off
      {% elif is_state_attr('climate.daikin_studio', 'swing_mode', 'Vertical') %}
        on
      {% elif is_state_attr('climate.daikin_studio', 'swing_mode', 'Horizontal') %}
        on
      {% else %}
        on
      {% endif %}

    # fan mode switch for UI.
    fan_mode_template: >-
      {% if is_state_attr('climate.daikin_studio', 'fan_mode', 'Auto') %}
        auto
      {% elif is_state_attr('climate.daikin_studio', 'fan_mode', 'Silence') %}
        low
      {% elif is_state_attr('climate.daikin_studio', 'fan_mode', '1') %}
        low
      {% elif is_state_attr('climate.daikin_studio', 'fan_mode', '2') %}
        medium
      {% elif is_state_attr('climate.daikin_studio', 'fan_mode', '3') %}
        medium
      {% elif is_state_attr('climate.daikin_studio', 'fan_mode', '4') %}
        fan_high
      {% elif is_state_attr('climate.daikin_studio', 'fan_mode', '5') %}
        fan_high
      {% else %}
      {% endif %}

    # temperature select for UI.
    target_temperature_template: "{{ states.climate.daikin_studio.attributes.temperature }}"

    modes:
      - 'fan_only'
      - 'dry'
      - 'cool'
      - 'heat'
      - 'heat_cool'
      - 'off'

    min_temp: 7
    max_temp: 35

    # example action
    set_hvac_mode:

      # send the climates current state to esphome.
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.daikin_studio
          hvac_mode: "{{ states('climate.daikin_studio_homekit') }}"

    set_temperature:
      - service: climate.set_temperature
        target:
          entity_id: climate.daikin_studio
        data:
          temperature: "{{ states.climate.daikin_studio_homekit.attributes.temperature }}"
```

Probably i'm missing something:
![2022-08-17_15-21-39_175](https://user-images.githubusercontent.com/52299148/185144739-c17a08ed-6771-4497-893f-9768a237fb6e.png)

As you can see, the two climate entities are perfectly synced, but I can't do any action.
If I chage the HVAC mode from my Climate Template, nothing happens.

What am I missing?

Thank you.

PS: is there a topic on the community forum? Didn't find it...

**Comment by NdR91** [comment]
At the end I managed to get it working. Alsi, I found how to adapt it for a Daikin Climate and in order to get it working properly on homekit:

```yaml
climate:
  - platform: climate_template
    name: Daikin Studio Homekit
    modes:
      - "auto"
      - "dry"
      - "off"
      - "cool"
      - "fan_only"
    min_temp: 7
    max_temp: 35
    # Template dati
    current_temperature_template: "{{ states.climate.daikin_studio.attributes.current_temperature }}"
    current_humidity_template: "{{ states('sensor.cucina_humidity_filtered') }}"
    availability_template: >-
      {% if states('climate.daikin_studio') in ['fan_only', 'dry', 'cool', 'heat', 'heat_cool', 'off']  %}
        true
      {% else %}
        false
      {% endif %}
    # Servizi
    set_hvac_mode:
      service: script.daikin_studio_homekit_hvac
    set_fan_mode:
      service: script.daikin_studio_homekit_fan
    set_temperature:
      service: script.daikin_studio_homekit_temperature
    temp_step: 1
    set_swing_mode:
      service: script.daikin_studio_homekit_swing
# Script Servizi
script:
  daikin_studio_homekit_hvac:
    alias: "Daikin Studio Homekit - HVAC"
    sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.daikin_studio
        data:
          hvac_mode: '{{ states("climate.daikin_studio_homekit") }}'
  daikin_studio_homekit_fan:
    alias: "Daikin Studio Homekit - FAN"
    sequence:
      - service: climate.set_fan_mode
        target:
          entity_id: climate.daikin_studio
        data:
          fan_mode: >
            {% if is_state_attr('climate.daikin_studio_homekit', 'fan_mode', 'auto') %}
              Auto
            {% elif is_state_attr('climate.daikin_studio_homekit', 'fan_mode', 'low') %}
              Silence
            {% elif is_state_attr('climate.daikin_studio_homekit', 'fan_mode', 'medium') %}
              2
            {% elif is_state_attr('climate.daikin_studio_homekit', 'fan_mode', 'high') %}
              4
            {% else %}
            {% endif %}
  daikin_studio_homekit_temperature:
    alias: "Daikin Studio Homekit - TEMP"
    sequence:
      - service: climate.set_temperature
        target:
          entity_id: climate.daikin_studio
        data:
          temperature: "{{ states.climate.daikin_studio_homekit.attributes.temperature }}"
          hvac_mode: '{{ states("climate.daikin_studio_homekit") }}'
  daikin_studio_homekit_swing:
    alias: "Daikin Studio Homekit - SWING"
    sequence:
      - service: climate.set_swing_mode
        target:
          entity_id: climate.daikin_studio
        data:
          swing_mode: >
            {% if is_state_attr('climate.daikin_studio_homekit', 'swing_mode', 'on') %}
              3D
            {% elif is_state_attr('climate.daikin_studio_homekit', 'swing_mode', 'off') %}
              Off
            {% else %}
            {% endif %}
```
