### ISSUE TITLE
Platform error climate.climate_template - cannot import name 'ClimateEntityFeature'

### ISSUE THREAD

**Issue by sdpeixoto** [jcwillox/hass-template-climate#23]
### The problem

[@jcwillox](https://github.com/jcwillox) First of all, a special thanks to you for the contribution that you have done to make this component available to the community free of charge!
I would like to use it, and first step was to install it in my hass docker environment, by copying the files from “climate_template” to “custom_components” folder.
/docker/appdata/homeassistant/custom_components/climate_template$ ls -ltr
-rw-rw-r--+ 1 sdpeixoto docker   352 Aug 29 03:49 manifest.json
-rw-rw-r--+ 1 sdpeixoto docker    38 Aug 29 03:49 __init__.py
-rw-rw-r--+ 1 sdpeixoto docker 20656 Aug 29 03:49 climate.py
drwxrwxr-x+ 2 root      root    4096 Oct 23 09:46 __pycache__

Second, I start defining my first climate device following the examples shared by you and that’s where I got struggle with it.

- platform: climate_template
  name: "Office Fan"
  icon_template: mdi:air-conditioner
  modes:
    - "auto"
    - "off"
    - "cool"
    - "heat"
  fan_modes:
    - "auto"
    - "low"
    - "medium"
    - "high"
  min_temp: "16"
  max_temp: "24"
  precision: "0.1"
  temp_step: "1"
  # get current temp.
  current_temperature_template: "{{ states('sensor.office_current_temperature') }}"

If I validate the configurations, then I’m getting the following error message:
Platform error climate.climate_template - cannot import name 'ClimateEntityFeature' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)

Do you think that I have missed something? Thanks in advance for all time that this issue may receive attention from you.

### What version of Template Climate has the issue?

0.4.1

### What version of Home Assistant are you running?

2022.3.7

### What type of installation are you running?

Home Assistant Container

### Example YAML snippet

```yml
- platform: climate_template
  name: "Office Fan"
  icon_template: mdi:air-conditioner
  modes:
    - "auto"
    - "off"
    - "cool"
    - "heat"
  fan_modes:
    - "auto"
    - "low"
    - "medium"
    - "high"
  min_temp: "16"
  max_temp: "24"
  precision: "0.1"
  temp_step: "1"
  # get current temp.
  current_temperature_template: "{{ states('sensor.office_current_temperature') }}"
```

### Anything in the logs that might be useful for us?

```python3
Configuration invalid

Platform error climate.climate_template - cannot import name 'ClimateEntityFeature' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)
```
