### ISSUE TITLE
Set_temperature error

### ISSUE THREAD

**Issue by thundershare** [jcwillox/hass-template-climate#35]
### The problem

Hi guys,

when i try to call set_temperature home assistant return this error... but to mee seems same code of example... where i wrong?

### What version of Template Climate has the issue?

0.6.0

### What version of Home Assistant are you running?

2023.1.6

### What type of installation are you running?

Home Assistant Container

### Example YAML snippet

```yml
climate:
  - platform: climate_template
    name: test climate
    modes:
      - "off"
      - "heat_cool"
    min_temp: 16
    max_temp: 30
    temp_step: 0.5
    current_temperature_template: "{{ states('sensor.testairz') }}"
    set_temperature:
      - service: pyscript.hvac_setlocal
        data:
          temperature: "{{ state_attr('climate.test_climate', 'temperature') | int }}"
```

### Anything in the logs that might be useful for us?

```python3
Error rendering data template: ValueError: Template error: int got invalid input 'None' when rendering template '{{ state_attr('climate.test_climate', 'temperature') | int }}' but no default was specified
```

### Additional information
This what HA return in developer section:
hvac_modes:
  - 'off'
  - heat_cool
min_temp: 16
max_temp: 30
target_temp_step: 1
current_temperature: 22
target_temp_high: null
target_temp_low: null
friendly_name: test climate
supported_features: 2

Seems missing temperature and hvac_mode variables
