### ISSUE TITLE
Unable to see/set target temperature

### ISSUE THREAD

**Issue by THorst92** [jcwillox/hass-template-climate#39]
### The problem

If I add a climate template entity, no target temperature is displayed. Also I am unable to set a temperature via the gui.
![image](https://user-images.githubusercontent.com/22470970/230067037-2be7bfea-a5c7-40fe-8869-2b72ffb219dd.png)
![image](https://user-images.githubusercontent.com/22470970/230067094-797ea6df-888b-4f42-91e6-5b63916a36ef.png)

I checked the template `state_attr('climate.eg05_heizung_links', 'temperature')` and the correct value is returned.

### What version of Template Climate has the issue?

0.6.1

### What version of Home Assistant are you running?

2023.03.3

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yml
- platform: climate_template
  name: eg05_heizung_template
  modes:
    - "auto"
    - "heat"
    - "off"
  min_temp: 4.5
  max_temp: 30.5
  temp_step: 0.5

  # get current temp.
  current_temperature_template: "{{ states('sensor.eg05_heizung_links_actual_temperature') }}"
  target_temperature_template: "{{ state_attr('climate.eg05_heizung_links', 'temperature') }}"
  target_temperature_high_template: "{{ state_attr('climate.eg05_heizung_links', 'max_temp') }}"
  target_temperature_low_template: "{{ state_attr('climate.eg05_heizung_links', 'min_temp') }}"
```
