### ISSUE TITLE
target_temperature not visible

### ISSUE THREAD

**Issue by 1iverea9er** [jcwillox/hass-template-climate#41]
### The problem

if `target_temperature_template` not configured, bat `target_temperature_high_template` and `target_temperature_low_template` configured as:

> 

    climate:
      - platform: climate_template
        name: TRV LR
        availability_template: >
            {{ (is_state('switch.trv_lr_cool_switch', 'on') or is_state('switch.trv_lr_cool_switch', 'off')) and 
              (is_state('switch.trv_kn_cool_switch', 'on') or is_state('switch.trv_kn_cool_switch', 'off')) }}
        current_temperature_template: "{{ states('sensor.livingroom_heatindex') }}"
        current_humidity_template: "{{ states('sensor.filtered_humidity_lr') }}"
        target_temperature_high_template: "{{ states('number.trv_lr_target_temperature_high') }}"
        target_temperature_low_template: "{{ states('number.trv_lr_target_temperature_low') }}"

target temperature not visible
<img width="405" alt="image" src="https://github.com/jcwillox/hass-template-climate/assets/82063500/0d373875-df1f-42af-95d3-2dcd809b08a3">

I assumed that the integration would output two values of the target temperature as it is done for the integration of thermostat in [ESPHome](https://esphome.io/components/climate/thermostat.html)

### What version of Template Climate has the issue?

0.6.1

### What version of Home Assistant are you running?

2023.5.3

### What type of installation are you running?

Home Assistant Supervised

### Example YAML snippet

```yml
climate:
  - platform: climate_template
    name: TRV LR
    availability_template: >
        {{ (is_state('switch.trv_lr_cool_switch', 'on') or is_state('switch.trv_lr_cool_switch', 'off')) and 
          (is_state('switch.trv_kn_cool_switch', 'on') or is_state('switch.trv_kn_cool_switch', 'off')) }}
    current_temperature_template: "{{ states('sensor.livingroom_heatindex') }}"
    current_humidity_template: "{{ states('sensor.filtered_humidity_lr') }}"
    target_temperature_high_template: "{{ states('number.trv_lr_target_temperature_high') }}"
    target_temperature_low_template: "{{ states('number.trv_lr_target_temperature_low') }}"
```
