### ISSUE TITLE
How to change the target temperature when controlling the AC with an IR control

### ISSUE THREAD

**Issue by cheusovalexandr** [jcwillox/hass-template-climate#47]
### The problem

Always sends 21.0 when target temperature changes

AC template:
```
  - platform: climate_template
    unique_id: bedroom_air_conditioner
    name: Bedroom Air Сonditioner
    modes:
      - "heat"
      - "dry"
      - "off"
      - "cool"
      - "fan_only"
    min_temp: 16
    max_temp: 31
    temp_step: 0.5
    
    availability_template: "{{ is_state('binary_sensor.ir', 'on') }}"
    current_temperature_template: "{{ states('sensor.0x00158d00045c0ced_temperature') }}"
    current_humidity_template: "{{ states('sensor.0x00158d00045c0ced_humidity') }}"
    target_temperature_template: "{{ state_attr('climate.bedroom_air_conditioner', 'temperature') }}"
    target_temperature_low_template: "{{ state_attr('climate.bedroom_air_conditioner', 'min_temp') }}"
    target_temperature_high_template: "{{ state_attr('climate.bedroom_air_conditioner', 'max_temp') }}"
    
    set_temperature:
      - service: script.turn_on
        entity_id: script.bedroom_air_conditioner_temperature
        data:
          variables:
            temperature: "{{ state_attr('climate.bedroom_air_conditioner', 'temperature')|float }}"
    set_hvac_mode:
      - service: script.turn_on
        entity_id: script.bedroom_air_conditioner_hvac_mode
        data:
          variables:
            hvac_mode: "{{ states('climate.bedroom_air_conditioner') }}"
```

Script:
```
  bedroom_air_conditioner_temperature:
    alias: bedroom_air_conditioner_temperature
    sequence:
    - if: "{{ temperature == 16.0 }}"
      then:
      - service: remote.send_command
        entity_id: remote.xiaomi_miio_192_168_1_57
        data:
          command: "ac_16"
    - if: "{{ temperature == 16.5 }}"
      then:
      - service: remote.send_command
        entity_id: remote.xiaomi_miio_192_168_1_57
        data:
          command: "ac_16_5"
```

### What version of Template Climate has the issue?

0.6.1

### What version of Home Assistant are you running?

Home Assistant 2023.7.2
Supervisor 2023.07.1

### What type of installation are you running?

supervised
