### ISSUE TITLE
Target Temperature is never displayed and can't be set, also fan modes are not displayed

### ISSUE THREAD

**Issue by escamoteur** [jcwillox/hass-template-climate#50]
### The problem

Hi,

I was really be thrilled to find your virtual climate package unfortunately it does not work as expects.
this is my config

```yaml
- platform: climate_template
    name: Klima Wohnzimmer
    unique_id: 8f58e31a-2df2-4399-91f4-8430849fe8c2
    modes:
      - "auto"
      - "heat"
      - "dry"
      - "off"
      - "cool"
      - "fan_only"
    fan_modes:
      - "auto"
      - "low"
      - "medium"
      - "high"
    min_temp: 16
    max_temp: 30

    # get current temp.
    current_temperature_template: "{{ states('sensor.temp_wohnzimmer_temperature') }}"


    # get current humidity.
    current_humidity_template: "{{ states('sensor.temp_wohnzimmer_humidity') }}"
```

But on my dashboard I only see:

![image](https://github.com/jcwillox/hass-template-climate/assets/16635729/1f4ce720-60d0-40bb-936c-a7d0def253c8)
![image](https://github.com/jcwillox/hass-template-climate/assets/16635729/1e4a4cb8-7166-45bf-ad0b-8e13fc22fa78)

and if I try to change the temperature I get an error.
In the attributes I only see:
![image](https://github.com/jcwillox/hass-template-climate/assets/16635729/46fa075a-3ab3-4616-826f-906407fc10e3)

I would like to use the component inside another automation that only queries the states of this attributes, but unfortunately it doesn't work.

### What type of installation are you running?

Home Assistant OS

**Comment by holymountain92** [comment]
same issue here, would like to use this to configure my HRU

**Comment by nicolaus-hee** [comment]
Missing target temperature: Have you tried populating `target_temperature_template`, as well? Is missing in your YAML.

Setting target temperature: Check [this example](https://github.com/jcwillox/hass-template-climate#example-action-to-control-existing-home-assistant-devices) from the readme.

**Comment by nicolaus-hee** [comment]
I am facing related troubles fitting well to this issue's title. 

My YAML looks like this:

````
climate:
  - platform: climate_template
    name: Heizung Badezimmer Clone
    unique_id: heizung_badezimmer_clone
    modes:
      - "auto"
      - "off"
      - "heat"
    min_temp: 7
    max_temp: 25
    target_temperature_template: "{{ state_attr('climate.heizung_badezimmer', 'temperature') }}"
    current_temperature_template: "{{ state_attr('climate.heizung_badezimmer', 'current_temperature') }}"
````

The state of `climate.heizung_badezimmer` from which the above is to somewhat clone is:

````
hvac_modes:
  - heat
  - "off"
min_temp: 8
max_temp: 28
preset_modes:
  - eco
  - comfort
current_temperature: 21
temperature: 16
preset_mode: eco
battery_low: false
battery_level: 100
holiday_mode: false
summer_mode: false
window_open: false
friendly_name: Heizung Badezimmer
supported_features: 17
````

However, `target_temperature_template` in `heizung_badezimmer_clone` is not shown:

````
hvac_modes:
  - auto
  - "off"
  - heat
min_temp: 7
max_temp: 25
target_temp_step: 1
current_temperature: 21
friendly_name: Heizung Badezimmer Clone
supported_features: 0
````

Consequently, I also have no target temperature in the GUI.

![aa](https://github.com/jcwillox/hass-template-climate/assets/48563755/cdad0135-060b-484c-b157-e4c8341c1cdf)


What am I doing wrong?

**Comment by escamoteur** [comment]
I'm pretty sure I tried it but in the examples I don't see a target temp template. (maybe I m just blind)
Am 17. Nov. 2023, 18:37 +0100 schrieb nicolaus-hee ***@***.***>:

**Comment by nicolaus-hee** [comment]
It's true that it is not included in the readme example but it's listed as an option in the readme and your YAML doesnt included it, at least the part you pasted above. So I'd give that a go. [I've tried and still don't see it](https://github.com/jcwillox/hass-template-climate/issues/50#issuecomment-1816835191), though.

**Comment by escamoteur** [comment]
My suspicion is that something in HomeAssistant has changed since this repository was last maintained. Unfortunately I don't have the time to learn how to build integrations in python to debug the problem
Am 17. Nov. 2023, 18:48 +0100 schrieb nicolaus-hee ***@***.***>:

**Comment by nicolaus-hee** [comment]
OK, let's say:

1. `climate.thermostat_entity` = your original climate entity, e.g. thermostat on radiator

2. `klima_wohnzimmer` = `unique_id` of your virtual climate device (which you named "Klima Wohnzimmer") which `climate_template` will turn into a climate entity named `climate.klima_wohnzimmer`. You need to add `unique_id: klima_wohnzimmer` to your conf for later reference.

On to your two questions:

To see the current target temperature set on `climate.thermostat_entity` also on `climate.klima_wohnzimmer`, try adding:

````
target_temperature_template: "{{ state_attr('climate.thermostat_entity', 'temperature') }}"
````

To make the target temperature of `climate.thermostat_entity` change when you change / set it on your virtual "Klima Wohnzimmer" entity, you need to add an action to your configuration, like so (untested):

````
  unique_id: klima_wohnzimmer
  set_temperature:
    - service: climate.set_temperature
      data:
        entity_id: climate.thermostat_entity
        temperature: "{{ state_attr('climate.klima_wohnzimmer', 'temperature') }}"
````

**Comment by holymountain92** [comment]
Even with the config to the basics it doesn't work. current_ is displayed correctly, target_ isn't.
<img width="554" alt="Screenshot 2023-11-18 at 17 27 41" src="https://github.com/jcwillox/hass-template-climate/assets/71234965/9872ae6f-9626-4289-9d43-68b5db388709">


      
```
    target_temperature_template: "30.0"
    
      # get current temp.
    current_temperature_template: "20.0"

    # get current humidity.
    current_humidity_template: "66.0"

```

**Comment by escamoteur** [comment]
Do I have to set my real climate entity there? I thought this template would create a pure virtual one that I can use to control my custom automation with?

Dies it work for you with your settings?
Am 18. Nov. 2023, 16:50 +0100 schrieb nicolaus-hee ***@***.***>:

**Comment by nicolaus-hee** [comment]
> Dies it work for you with your settings?

As mentioned before: No. But I was hoping I did something wrong and it'd work for you guys.

**Comment by scuba75** [comment]
You have to have a `set_temperature` action.
Can set it to control a number template

**Comment by escamoteur** [comment]
I got it working:

```yaml
  - platform: climate_template
    name: Test Thermostat
    unique_id: 76c49564-3347-4a48-8732-cf88ee6729ff
    modes:
      - "auto"
      #     - "dry"
      - "off"
    #      - "cool"
    #      - "heat"
    #     - "fan_only"
    fan_modes:
      - "auto"
      - "low"
      - "medium"
      - "high"
    min_temp: 16
    max_temp: 30

    # get current temp.
    current_temperature_template: "{{ states('sensor.temp_wohnzimmer_temperature') }}"

    # get current humidity.
    current_humidity_template: "{{ states('sensor.temp_wohnzimmer_humidity') }}"

    set_temperature:
      - service: input_number.set_value
        data:
          entity_id: input_number.ziel_temp_wohnzimmer
          value: "{{ state_attr('climate.test_thermostat', 'temperature') }}"
    set_fan_mode:
      - service: input_text.set_value
        data:
          entity_id: input_text.hvac_mode_wohnzimmer
          value: "{{ state_attr('climate.test_thermostat', 'fan_mode') }}"
```
