### ISSUE TITLE
Cant set Target temp low and Target temp high with thermostat entity when in heat/cool mode

### ISSUE THREAD

**Issue by darkwolfgar** [jcwillox/hass-template-climate#53]
### The problem

```
climate:
  - platform: climate_template
    name: Test Thermostat
    unique_id: 76c49564-3347-4a48-8732-cf88ee6729ff
    modes:
      - "auto"
      - "heat"
      - "cool"
      - "heat_cool"
      - "fan_only"
      - "off"
    min_temp: 60
    max_temp: 80

    current_temperature_template: "{{ states('sensor.living_room_temperature_temperature') }}"
    current_humidity_template: "{{ states('sensor.living_room_temperature_humidity') }}"

    set_temperature:
      - service: input_number.set_value
        data:
          entity_id: input_number.virtual_target_temperature
          value: "{{ state_attr('climate.test_thermostat', 'temperature') | float(0) }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.virtual_target_temp_high
          value: "{{ state_attr('climate.test_thermostat', 'target_temp_high') | float(0) }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.virtual_target_temp_low
          value: "{{ state_attr('climate.test_thermostat', 'target_temp_low') | float(0) }}"
```

This is currently my code, it will work to set a single target temperature, however it does not show a range to set like it should with heat/cool or auto mode enabled. 

### What version of Template Climate has the issue?

0.6.1

### What version of Home Assistant are you running?

2023.11.6

### What type of installation are you running?

Home Assistant Supervised
