### ISSUE TITLE
Cannot use numerical fan speed modes. ['auto', '1', '2', '3']

### ISSUE THREAD

**Issue by CV8R** [jcwillox/hass-template-climate#62]
### The problem

Cannot use numerical fan speed modes.

Log reports Received invalid fan mode: 1. Expected: ['auto', '1', '2', '3'] and state does not update.

### What version of Template Climate has the issue?

v0.6.1

### What version of Home Assistant are you running?

 Core 2024.2.5 Supervisor 2024.02.1 Operating System 12.0 Frontend 20240207.1

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```python3
ERROR (MainThread) [custom_components.climate_template.climate] Received invalid fan mode: 1. Expected: ['auto', '1', '2', '3'].
```

**Comment by litinoveweedle** [comment]
Hello,

I checked the code at place and it seems to be issue with integer input vs string expected in comparison. I can try to make fix for this in my [forked repo](https://github.com/litinoveweedle/hass-template-climate) if you are willing to test the patch.

**Comment by litinoveweedle** [comment]
BTW I am not sure, if numeric values are supported. I did checked all core Homeassistant [constants](https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/const.py):
```
# Possible fan state
FAN_ON = "on"
FAN_OFF = "off"
FAN_AUTO = "auto"
FAN_LOW = "low"
FAN_MEDIUM = "medium"
FAN_HIGH = "high"
FAN_TOP = "top"
FAN_MIDDLE = "middle"
FAN_FOCUS = "focus"
FAN_DIFFUSE = "diffuse"
```

from those climate_template imports only subset:
```
    FAN_AUTO,
    FAN_LOW,
    FAN_MEDIUM,
    FAN_HIGH,
```

therefore using fan modes for Climate entity in climate_template shall use only this set of strings:

`"auto", "low", "medium", "high"`

Given error message is misleading as it seems to be returning enum values. Please test functionality with string as above - it should work. If so, then this is not a bug ;-)

**Comment by CV8R** [comment]
Hi @litinoveweedle I understood that the fan modes are allowed to be custom per Fan modes here:

[https://developers.home-assistant.io/docs/core/entity/climate/](url)

Granted, the Fan Modes are a list of strings, but as you say looks to treat them as integer and not str when using a numeric value.

Of course happy to test.

**Comment by litinoveweedle** [comment]
If I would prepare for you git branch in my repo with proposed fix, are you able to manually place it into your HA (modify climate.py)?

**Comment by CV8R** [comment]
Can add the climate.py and test.

Here is a cut down template that exhibits the issue.

```

  - platform: climate_template
    name: "Test AC"
    unique_id: 766fec37-6033-4206-b80a-a8ffde5ee2d9
    modes:
      - "fan_only"
      - "off"
    fan_modes:
      - "auto"
      - "1"
      - "2"
      - "3"
    current_temperature_template: "{{ states('climate.cc3f1d041688') }}"
    current_humidity_template: "{{ states('climate.cc3f1d041688') }}"
    hvac_mode_template: "{{ states('climate.cc3f1d041688') }}"
    target_temperature_template: "{{ states('climate.cc3f1d041688') }}"
    fan_mode_template: "{{ state_attr('climate.cc3f1d041688', 'fan_mode') | string }}"
    # actions
    set_fan_mode:
      - service: climate.set_fan_mode
        target:
          entity_id: climate.cc3f1d041688
        data:
          fan_mode: "{{ fan_mode }}"
```
