### ISSUE TITLE
off mode error

### ISSUE THREAD

**Issue by stepsolar** [jcwillox/hass-template-climate#65]
### The problem

I need your help, I wrote this code and it all works but when I turn off homeassistant it gives me an error, but the shutdown actually happens. How can I modify the code? Thank you

### What type of installation are you running?

None

### Example YAML snippet

```yml
climate:
  - platform: climate_template
    name: Termostato Sauna
    unique_id: termo_Sauna
    modes:
      - "off"
      - "heat"
      - "dry"
    min_temp: 40
    max_temp: 100
    min_humidity: 0
    max_humidity: 100
    temp_step: 1.0
    # sonda temperatura sauna
    current_temperature_template: "{{ states('sensor.spa_sonda_temp_sauna') }}"
    # sonda umidità sauna
    current_humidity_template: "{{ states('number.spa_setpoint_umid_biosauna') }}" #per il momento metto il setpoint dopo metto la sonda di umidità
    # setpoit temperatura Sauna
    target_temperature_template: "{{states ('number.spa_setpoint_temp_sauna') }}"
    # setpoit umidità Sauna
    target_humidity_template: "{{states ('number.spa_setpoint_umid_biosauna') }}" 
    
    set_temperature:
      - service: number.set_value
        entity_id: number.spa_setpoint_temp_sauna
        data:
          value: "{{ temperature }}"
    set_humidity:      
      - service: number.set_value
        entity_id: number.spa_setpoint_umid_biosauna
        data:
          value: "{{ humidity }}"
          
    hvac_action_template: "{{ state('switch.spa_termo_sauna_auto_off' ) }}"
   
    set_hvac_mode:
      - service: switch.turn_{{ 'off' if hvac_mode == 'off' else 'on' }}
        entity_id: switch.spa_termo_sauna_auto_off    
    #   - service: select.select_option
    #     data:
    #       entity_id: select.spa_sell_biosauna_sauna
    #       option: "{{ 'Biosauna' if hvac_mode == 'dry' else 'Sauna' if hvac_mode == 'heat' else 'off' if hvac_mode == 'off'}}"
      - service: switch.turn_{{ 'off' if hvac_mode == 'dry' else 'on' if hvac_mode == 'heat' }}
        entity_id: switch.spa_sel_on_sauna_off_biosauna
```
