### ISSUE TITLE
set_temperature does not work!

### ISSUE THREAD

**Issue by douglascrc-git** [jcwillox/hass-template-climate#67]
### The problem

I have this code 
`  - platform: climate_template
    name: Bedroom Aircon
    modes:
      - "heat"
      - "off"
      - "cool"
    min_temp: 5
    max_temp: 30

    # get current temp.
    current_temperature_template: "{{ states('sensor.temperatura_termostato_baterias') }}"

    # get current humidity.
    current_humidity_template: "{{ states('sensor.sensorhumedadytemperatura_humidity') }}"
    target_temperature_template: "{{ state_attr('climate.termostato_zona_z1', 'temperature') }}"
    # set current temp.
    set_temperature:
      - condition: template
        value_template: "{{ state_attr('climate.termostato_zona_z1', 'temperature') != state_attr('climate.Bedroom_Aircon', 'temperature') }}"
      - service: climate.set_temperature
        data:
          entity_id: climate.termostato_zona_z1
          temperature: "{{ state_attr('climate.Bedroom_Aircon', 'temperature') }}"
`

I've been trying to get the Bedroom Aircon thermostat to obtain the target temperature from the termostato_zona_z1 thermostat and, moreover, when I change the target temperature of the Bedroom Aircon, it should also modify the temperature of the termostato_zona_z1 thermostat. But for some reason, the set_temperature action isn't working.

I tried removing this line `target_temperature_template: "{{ state_attr('climate.termostato_zona_z1', 'temperature') }}`", and the set_temperature action works. But leaving both lines doesn't work.

Is there any way to solve this?

### What type of installation are you running?

None

### Example YAML snippet

```yml
- platform: climate_template
    name: Bedroom Aircon
    modes:
      - "heat"
      - "off"
      - "cool"
    min_temp: 5
    max_temp: 30

    # get current temp.
    current_temperature_template: "{{ states('sensor.temperatura_termostato_baterias') }}"

    # get current humidity.
    current_humidity_template: "{{ states('sensor.sensorhumedadytemperatura_humidity') }}"
    target_temperature_template: "{{ state_attr('climate.termostato_zona_z1', 'temperature') }}"
    # set current temp.
    set_temperature:
      - condition: template
        value_template: "{{ state_attr('climate.termostato_zona_z1', 'temperature') != state_attr('climate.Bedroom_Aircon', 'temperature') }}"
      - service: climate.set_temperature
        data:
          entity_id: climate.termostato_zona_z1
          temperature: "{{ state_attr('climate.Bedroom_Aircon', 'temperature') }}"
```

**Comment by andrus2049** [comment]
IMO you can't call 
` service: climate.set_temperature`
inside the climate template `set_temperature`:, because it's calling itself.

When temperature is set on the card, you have to directly invoke your specific device function (aircon), and in the service call or property set you can refer to the {{ temperature }} value

ex.:

```python
          sequence:
            - service: number.set_value
              data:
                value: "{{ temperature | float(1) }}"
              target:
                 xxxxxxxxxxxxx
```

**Comment by douglascrc-git** [comment]
> IMO you can't call ` service: climate.set_temperature` inside the climate template `set_temperature`:, because it's calling itself.
> 
> When temperature is set on the card, you have to directly invoke your specific device function (aircon), and in the service call or property set you can refer to the {{ temperature }} value
> 
> ex.:
> 
> ```python
>           sequence:
>             - service: number.set_value
>               data:
>                 value: "{{ temperature | float(1) }}"
>               target:
>                  xxxxxxxxxxxxx
> ```

I did as you told me, but still not working. 

The same behavior: I can change Bedroom Aircon target temperature from termostato_z1 but I can't change termostato_z1 target temperature from Bedroom Aircon.

This is my code now:

`  - platform: climate_template
    name: Bedroom Aircon
    modes:
      - "heat"
      - "off"
      - "cool"
    min_temp: 5
    max_temp: 30

    # get current temp.
    current_temperature_template: "{{ states('sensor.temperatura_termostato_baterias') }}"

    # get current humidity.
    current_humidity_template: "{{ states('sensor.sensorhumedadytemperatura_humidity') }}"
    target_temperature_template: "{{ state_attr('climate.termostato_zona_z1', 'temperature') }}"
    # set current temp.
    set_temperature:
      - condition: template
        value_template: "{{ state_attr('climate.termostato_zona_z1', 'temperature') != state_attr('climate.Bedroom_Aircon', 'temperature') }}"
      - service: number.set_value
        data:
          value: "{{ temperature | float(1) }}"
          target: climate.termostato_zona_z1`

**Comment by andrus2049** [comment]
You need to directly address the aircon entity (input.number temperature ???) if you want to set the new temperature.
You can't use a climate entity as target, the climate entity is the software controller.

Let say that my_aircon temperature is controlled by a number entity.

```
set_temperature:
  - condition: template
    value_template: "{{ temperature != states('number.my_aircon_temperature') }}"
  - service: number.set_value
    data:
      value: "{{ temperature | float(1) }}"
      target: 
        entity_id: number.my_aircon_temperature

``` 

Condition template might be unnecessary as the temperature can  be set anyway, also if it's just the current one.
