### ISSUE TITLE
Struggling to get it to create entity

### ISSUE THREAD

**Issue by markbw999** [jcwillox/hass-template-climate#77]
### The problem

Hi,
I'm trying to create a very basic climate entity to use with a thermostat card purely for display purposes. I thought this would be great as most of the parameters seem to be optional. I have added the following yaml to my config file but it doesn't appear to create anything.

climate:
  - platform: climate_template
    name: "Upstairs Thermostat"
    min_temp: 10
    max_temp: 30
    current_temperature_template: "{{ states('sensor.west_wing_t_h_temperature') }}"
    current_humidity_template: "{{ states('sensor.west_wing_t_h_humidity') }}"
    target_temperature_template: "{{ states('input_number.upstairs_target_temperature') }}"

Am I trying to do something stupid that isn't supported or have I made a basic error?

Thanks, Mark

### What version of Template Climate has the issue?

0.8.0

### What version of Home Assistant are you running?

2024.11.1

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yml
climate:
  - platform: climate_template
    name: "Upstairs Thermostat"
    min_temp: 10
    max_temp: 30
    current_temperature_template: "{{ states('sensor.west_wing_t_h_temperature') }}"
    current_humidity_template: "{{ states('sensor.west_wing_t_h_humidity') }}"
    target_temperature_template: "{{ states('input_number.upstairs_target_temperature') }}"
```
