### ISSUE TITLE
Changes in target_temperature_template value triggers the custom set_temperature action

### ISSUE THREAD

**Issue by mohoo** [jcwillox/hass-template-climate#79]
### The problem

Example:
```
climate:
  - platform: climate_template
    name: Sleeping Room
    target_temperature_template: "{{ state_attr('climate.sleeping_room_heater', 'temperature') }}"
    set_temperature:
      - action: input_number.set_value
        metadata: {}
        data:
          value: "{{ temperature }}"
        target:
          entity_id: input_number.sleeping_room_scheduled_target_temp
```
For example if I change the climate.sleeping_room_heater target temp by an Window Open Automation the set_temperature action is also triggerd, because the target_temperature_template detects any changes. However, this overwrites my input number, which I need to restore the previous temperature after closing the window. 

Bug summarised: target_temperature_template or any templates must not trigger actions as a side effect. IMHO

### What type of installation are you running?

None
