### ISSUE TITLE
climate.turn_off not compatible after upgradde

### ISSUE THREAD

**Issue by arthurperezbessa** [jcwillox/hass-template-climate#89]
### The problem

I just upgraded my Home Assistant and I'm having issues with my climates. When I press to turn off, this message is shown: 
'Entity climate.air_conditioner does not support action climate.turn_off.'

### What version of Template Climate has the issue?

v0.8.0

### What version of Home Assistant are you running?

2025.1.0

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yml
##### Ar Quarto #####
- platform: climate_template
  name: Ar Quarto
  unique_id: ar_quarto
  modes:
    - "cool"
    - "off"
  min_temp: 18
  max_temp: 30
  fan_modes:
    - "auto"
    - "low"
    - "medium"
    - "high"

  # Disponibilidade - Caso tenha algums dispositivo ligado a ele
  availability_template: >
          {% if is_state('sensor.smart_ir_quarto_learned_ir_code', 'unavailable') or is_state('binary_sensor.zigbee2mqtt_bridge_connection_state_2', 'off') %}
            false
          {% else %}
            true
          {% endif %}

  # Modo
  hvac_mode_template: "{{ states('input_select.ar_quarto_modo') }}"

  set_hvac_mode:
  - service: input_select.select_option
    target:
      entity_id: input_select.ar_quarto_modo
    data:
      option: "{{ hvac_mode }}"

  # Temperatura
  target_temperature_template: "{{states ('input_number.ar_quarto_temperatura') }}"
  current_temperature_template: "{{ state_attr('weather.forecast_home', 'temperature' ) | int(0)}}"

  set_temperature:
    - service: input_number.set_value
      target:
        entity_id: input_number.ar_quarto_temperatura
      data:
        value: "{{ temperature }}"

  # Ventilador
  fan_mode_template: "{{ states('input_select.ar_quarto_fan') }}"

  set_fan_mode:
  - service: input_select.select_option
    target:
      entity_id: input_select.ar_quarto_fan
    data:
      option: "{{ fan_mode }}"
```

### Anything in the logs that might be useful for us?

```python3
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:12:57 (15 occurrences)
Last logged: 23:41:39

[548343185616] Entity climate.ar_escritorio does not support action climate.turn_off
[548343185616] Entity climate.ar_quarto does not support action climate.turn_off
[547395326384] Entity climate.ar_quarto does not support action climate.turn_off
[547395326384] Entity climate.ar_escritorio does not support action climate.turn_off
```
