### ISSUE TITLE
climate does not change to turn off when thermostat use AUTO mode

### ISSUE THREAD

**Issue by PetrMa** [jcwillox/hass-template-climate#90]
### The problem

Hi,
I have this issue after upgrade to HA to 2025.1. The same issue is in Climate template 1.0.0 and 0.8.0.

I use AUTO mode on my thermostats to turn them on, which is triggered by automation when the temperature in the room drops below a certain level.
This works correctly and when the temperature drops, the physical thermostat switches to AUTO mode and starts heating.
In HA version 2024.12 and lower, it worked so that the thermostat was set to AUTO and the climate template reported the status as HEAT and the hvac action as HEATING
in HA version 2025.1, after starting the thermostat, the climate template reports the status as OFF and the hvac action as HEATING.
Why in the new version of HA the climate template not show as HEAT but as OFF in this setting as it did in the previous HA version?

My climate template code is below.

### What version of Template Climate has the issue?

1.0.0

### What version of Home Assistant are you running?

2025.1.1

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yml
- platform: climate_template
  name: Termostat ložnice
  modes:
    - "off"
    - "heat"
  min_temp: 5
  max_temp: 35
  temp_step: 0.5
  precision: 0.1

  target_temperature_template: "{{ state_attr('climate.topeni_loznice', 'temperature') }}"
  target_temperature_high_template: "{{ states('number.topeni_loznice_max_temperature') }}"
  target_temperature_low_template: "{{ states('number.topeni_loznice_min_temperature') }}"
  availability_template: "{{ states('climate.topeni_loznice') != None }}"

  current_temperature_template: >
    {% if states('sensor.bt_loznice_teplota') != None %}
      {{ states('sensor.bt_loznice_teplota') }}
    {% else %}
      unavailable
    {% endif %}

  current_humidity_template: >
    {% if states('sensor.bt_loznice_vlhkost') != None %}
      {{ states('sensor.bt_loznice_vlhkost') }}
    {% else %}
      unavailable
    {% endif %}

  hvac_action_template: >
    {% if state_attr('climate.topeni_loznice', 'hvac_action') == "heating" %}
      heating
    {% else %}
      off
    {% endif %}

  hvac_mode_template: >
    {% if states('sensor.topeni_loznice_force') == "normal" %}
      heat
    {% else %}
      off
    {% endif %}

  set_hvac_mode:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.topeni_loznice
        hvac_mode: >-
          {% if hvac_mode == 'off' %}
            off
          {% else %}
            auto
          {% endif %}

  set_temperature:
    - service: climate.set_temperature
      data:
        entity_id: climate.topeni_loznice
        temperature: "{{ temperature }}"
```

### Additional information

![image](https://github.com/user-attachments/assets/d34c489b-20e3-4d0f-b9ce-f391681267e1)
![image](https://github.com/user-attachments/assets/da3b9789-14db-4f63-9622-400530650b40)
