### ISSUE TITLE
preset_modes?

### ISSUE THREAD

**Issue by ptruman** [jcwillox/hass-template-climate#96]
### The problem

I've defined some but they are not showing?

```
  - platform: climate_template
    name: Studio Heater
    modes: [ "heat", "off" ]
    preset_modes: [ "activity", "comfort", "eco" ]
    min_temp: 0
    max_temp: 30
    precision: .1
    temp_step: .5
    # get current and target temp.
    current_temperature_template: "{{ state_attr('climate.studio_radiator', 'current_temperature') }}"
    target_temperature_template: "{{ state_attr('climate.studio_radiator', 'temperature') }}"
    # example action
    set_hvac_mode:
      - condition: state
        entity_id: input_boolean.studio_radiator_power
        state: "on"
    set_temperature:
      - service: input_number.set_value
        target:
          entity_id: climate.studio_radiator
        data:
           value: "{{ temperature }}"
```
What I get is this :

![Image](https://github.com/user-attachments/assets/d4b6ceba-e743-4428-a8b0-f00fef14c345)

What I'm expecting is something like:

![Image](https://github.com/user-attachments/assets/764e148c-3461-46cb-a6aa-633cffdf0750)

What am I invariably doing wrong?

### What version of Template Climate has the issue?

1.0.1

### What version of Home Assistant are you running?

2025.1.4

### What type of installation are you running?

Home Assistant Core

### Example YAML snippet

```yml

```

### Anything in the logs that might be useful for us?

```python3

```
