### ISSUE TITLE
[FR]: inherit template values from a default device

### ISSUE THREAD

**Issue by wjcarpenter** [jcwillox/hass-template-climate#98]
### Describe the solution you'd like

I think a common use case would be to wrap an existing climate device and tweak a few items. For that case, it would be really handy to be able to specify that existing device and have template values taken from it. Explicitly defined templates would, of course, take precedence.

**Comment by lukyjay** [comment]
Hey @wjcarpenter I wanted this too so I wrote the yaml. Note I used the fork of this project (https://github.com/litinoveweedle/hass-template-climate) but I think it will work here too.

My code to take values from climate.ac and create a better AC device which has the additional sensors:
```yaml
climate:
  - platform: climate_template
    name: Better Aircon
    unique_id: better_aircon
    hvac_modes:
      - "off"
      - "cool"
      - "heat"
      - "fan_only"
      - "dry"
    fan_modes:
      - "auto"
      - "low"
      - "medium"
      - "high"
    min_temp: 16
    max_temp: 30
    current_temperature_template: "{{ states('sensor.average_house_temperature') }}"
    target_temperature_template: "{{ state_attr('climate.ac', 'temperature') | int }}"
    current_humidity_template: "{{ states('sensor.average_house_humidity') }}"
    hvac_mode_template: "{{ states('climate.ac') }}"
    fan_mode_template: "{{ state_attr('climate.ac', 'fan_mode') }}"
    set_temperature:
      - service: climate.set_temperature
        data:
          entity_id: climate.ac
          temperature: "{{ state_attr('climate.better_aircon', 'temperature') | int }}"
    set_fan_mode:
      - service: climate.set_fan_mode
        data:
          entity_id: climate.ac
          fan_mode: "{{ state_attr('climate.better_aircon', 'fan_mode') }}"
    set_hvac_mode:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.ac
          hvac_mode: "{{ states('climate.better_aircon') }}"
          
```
